from typing import List, Optional


class CryptContext:
    def __init__(self, schemes: Optional[List[str]] = None, deprecated: Optional[str] = None):...
    def verify(self, plain_password:str, hashed_password:str) -> bool:...
    def hash(self, password:str) -> str:...
