version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
    - .:/app
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    env_file:
      - .env
    ports:
    - "5432:5432"
