version: '3'

services:
  app:
    container_name: fast-api-chess-server-app
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    env_file:
      - .env
    ports:
    - "5432:5432"
