version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.2
        environment:
          TEST_DB_CONNECTION: postgresql://postgres:postgres@localhost:5432/chess-fast-test
          SECRET_KEY: test
      - image: circleci/postgres:13.2-alpine
        environment:
          POSTGRES_DB: chess-fast-test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          command: |
            sudo pip install poetry
            poetry config virtualenvs.create false --local
            poetry install
            pytest
