version: 2.1

jobs:
  build-and-test:
    docker:
      - image: ubuntu-latest
    steps:
      - checkout
      - run:
        command: |
          docker-compose -f "docker-compose.yml" up -d build
