version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.2
        environment:
          TEST_DB_CONNECTION: postgresql://postgres:postgres@localhost:5432/chess-fast-test
          SECRET_KEY: test
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_DB: chess-fast-test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock"}}
      - run:
          command: |
            sudo pip install poetry
            poetry config virtualenvs.create false --local
            poetry install
            ls /usr/local/lib/python3.9/site-packages/
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock"}}
          paths:
            - "/usr/local/lib/python3.9/site-packages/"
      - run: pytest
