version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            cp .env.sample .env
            echo POSTGRES_PASSWORD=postgres >> .env
            docker-compose -f "docker-compose.yml" up -d --build
            
            docker exec fast-api-chess-server-app pytest
